<a href="https://colab.research.google.com/github/faiza-salman/Home-Learning-tasks/blob/main/HLT_week4_faiza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 2**

In [2]:
def mark_grade():
  global percentage
  percentage = (input("Please enter your marks " ))
  if percentage >= "90":
    print ("Your grade is A+")
    return "A+ grade"   
  elif percentage >= "85":
    print ("Your grade is A")
    return "A grade" 
  elif percentage >= "80":
    print ("Your grade is A-")
    return "A- grade"  
  elif percentage >= "75":
    print ("Your grade is B+")
    return "B+ grade"  
  elif percentage >= "70":
    print ("Your grade is B")
    return "B grade"
  elif percentage >= "65":
    print ("Your grade is C+")
    return "C+ grade" 
  elif percentage >= "60":
    print ("Your grade is C")
    return "C grade"
  elif percentage >= "55":
    print ("Your grade is D+")
    return "D+ grade"   
  elif percentage >= "50":
    print ("Your grade is D")
    return "D grade" 
  elif percentage >= "40":
    print ("Your grade is E")
    return "E grade"  
  elif percentage < "40":
    print ("Your grade is F")
    return "F grade"
    
x = mark_grade()
def ext(): 
  print("What is your target Grade?")
  ideal=(input())
  print ("Your target grade is ",ideal, " and your current grade is ",x )
  if percentage > ideal:
    print ("You are exceeding expectations!!!")
  elif percentage == ideal:
    print ("You are doing a great job!!!")
  else:
    print("You need to work hard to achieve your target grade")

ext()

Please enter your marks 85
Your grade is A
What is your target Grade?
A+
Your target grade is  A+  and your current grade is  A grade
You need to work hard to achieve your target grade


**1D array from 0-9**

In [3]:
import numpy as np
listA=[0,2,3,4,5,6,7,8,9]
print (listA)
print (type(listA))
A = np.array(listA)
print(A)
print(type(A))
print(A.ndim)

[0, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
[0 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


**Create a 3×3 NumPy array of all Boolean value Trues**

In [4]:
import numpy as np
a = np.ones(9, dtype= bool)
print(a)
print("the dimension of array is ",a.ndim)
b = a.copy()
b.resize (3,3)
print (b)
print("The shape of array is ",b.shape)
print("The dimension of the reshaped array is ",b.ndim)

[ True  True  True  True  True  True  True  True  True]
the dimension of array is  1
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
The shape of array is  (3, 3)
The dimension of the reshaped array is  2


**or**

In [5]:
import numpy as np
a = np.ones(9, dtype= bool).reshape(3,3)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**convert 1D array to 2D array with 2 rows**

In [6]:
import numpy as np
abc=np.array([1,2,3,4,5,6,7,8])
print (abc)
print("the dimension of array is ",abc.ndim)
new = abc.reshape (2,4)
print(new)
print("the dimension of array is ",new.ndim)

[1 2 3 4 5 6 7 8]
the dimension of array is  1
[[1 2 3 4]
 [5 6 7 8]]
the dimension of array is  2


**Extract all odd numbers from array of 1-10**

In [9]:
import numpy as np
B=[1,2,3,4,5,6,7,8,9,10]
print(B)
print(type(B))
array_B=np.array(B)
print(array_B)
print("Extracting all odd numbers from the array ",array_B [0:9:2]) # 0r[::2]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
Extracting all odd numbers from the array  [1 3 5 7 9]


**Replace all odd numbers in an array of 1-10 with the value -1**

In [8]:
import numpy as np
X=np.array([1,2,3,4,5,6,7,8,9,10]) #creating array with values
print(X)
newX = X.copy()
newX [::2]=(-1) #slicing [::interval]= value to be replaced with
print(newX)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


 **​Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals**

In [10]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print("array a =",a)
b = np.arange(10,19).reshape(3,3)
print("array b =",b)
c = np.dot(a,b)
print("The dot product of array a and b =", c)
sum=np.sum(c)
print("The sum of array a and b =", sum)
column = np.sum(c,axis=0) #column vise
print("The sum of arrays a and b by column =", column)
row=np.sum(c,axis=1)# row vise
print("The of arrays a and b by rows =", row)

array a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
array b = [[10 11 12]
 [13 14 15]
 [16 17 18]]
The dot product of array a and b = [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
The sum of array a and b = 1944
The sum of arrays a and b by column = [603 648 693]
The of arrays a and b by rows = [ 270  648 1026]
